---
  - name: Apt Update
    apt:
        update_cache: yes

  - name: Install Apache2
    apt:
        name: "{{ item }}" 
        update_cache: yes
        state: latest
    with_items: "{{ packages }}"

  - name: Download Node Exporter
    get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.0.0-rc.1/node_exporter-1.0.0-rc.1.linux-amd64.tar.gz
        dest: /home/geller/Downloads
        mode: 0777

  - name: Unarchive downloaded archive
    unarchive:
        src: /home/geller/Downloads/node_exporter-1.0.0-rc.1.linux-amd64.tar.gz
        dest: /usr/local/bin

  - name: Create service file 
    file:
        path: /etc/systemd/system/node_exporter.service
        state: touch
        mode: 0777

  - name: Insert credentials for service
    blockinfile:
        path: /etc/systemd/system/node_exporter.service
        block: |
            [Unit]
            Description=Node Exporter
            Wants=network-online.target
            After=network-online.target
            [Service]
            User=node_exporter
            Group=node_exporter
            ExecStart=/usr/local/bin/node_exporter
            [Install]
            WantedBy=default.target

  - name: Start Node Exporter
    systemd:
        state: started
        name: node_exporter

