---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: homework
spec:
  type: NodePort
  ports:
    - nodePort: 31234
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: nginx