---
  - name: Create file for PostgreSQL 9.6 repository
    file: 
        path: /etc/apt/sources.list.d/postgresql.list
        state: touch

  - name: Add repo to created file
    lineinfile:
        path: /etc/apt/sources.list.d/postgresql.list
        line: 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'

  - name: Import key to the system
    apt_key: 
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

  - name: Apt Update
    apt:
        update_cache: yes
  
  - name: Install PostgreSQL and ufw
    apt:
        name: "{{ item }}" 
        update_cache: yes
        state: latest
    with_items: "{{ packages }}"

  - name: Start PostgreSQL service
    service:
      name: postgresql
      state: started
      enabled: yes

  - name: Connect to DB
    become: true
    become_user: postgres
    postgresql_user:
      db: exam
      name: postgres
      password: Passw0rd
      priv: "ALL"

  - name: Allow SSH
    ufw: 
      default: allow
      name: /etc/init.d/ssh
 
  - name: Allow PotgreSQL
    ufw: 
      default: allow
      name: /etc/init.d/ssh

#  - name: Configure MASTER Server postgresql conf file
#    lineinfile: 
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: listen_addresses = '192.168.1.165'
 
#  - name: one
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: wal_level = hot_standby 

#  - name: two
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: synchronous_commit = local

#  - name: three
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: archive_mode = on

#  - name: four
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: archive_command = 'cp %p /var/lib/postgresql/9.6/main/archive/%f' 

#  - name: five
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: max_wal_senders = 2 

#  - name: six
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: wal_keep_segments = 10
 
#  - name: seven
#    lineinfile:
#      path: /etc/postgresql/9.6/main/postgresql.conf
#      line: synchronous_standby_names = 'pgslave001'

  - name: Create new direcotry dor the archive
    file:
      state: directory
      path: /var/lib/postgresql/9.6/main/archive/
      owner: postgres
      group: postgres
      mode: '0700'

#  - name: Configure file for authentication configuration
#    lineinfile:
#      path: /etc/postgresql/9.6/main/pg_hba.conf
#      line: "# Localhost\nhost    replication     replica          127.0.0.1/32            md5\n# PostgreSQL Master IP address\nhost    replication     replica          192.168.1.165/32        md5\n# PostgreSQL SLave IP address\nhost    replication     replica          192.168.1.157/32        md5"

  - name: Restart PostgreSQL
    service:
      name: postgresql
      state: restarted

  - name: Create Replica user
    become: true
    become_user: postgres
    postgresql_user:
      name: replica
      password: Passw0rd
      role_attr_flags: REPLICATION
